version: '3.8'

services:
  nats:
    image: nats:2
    container_name: nats
    command: "--jetstream -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - todo-list

  database:
    image: postgres:16
    container_name: database
    command: postgres -c 'max_connections=200'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend-master-class
    networks:
      - todo-list
    volumes:
      - "postgresData:/var/lib/postgresql/data"

volumes:
  postgresData:

networks:
  todo-list: